# Generated by Django 5.0.4 on 2024-04-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sector',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
